function [Counterparty,NettingID,Principal,Maturity,LegType,LegRateReceiving,LegRatePaying,LatestFloatingRate,Period] = importSwaps(workbookFile,sheetName,startRow,endRow)
    %IMPORTFILE1 Import data from a spreadsheet
    %   [Counterparty,NettingID,Principal,Maturity,LegType,LegRateReceiving,LegRatePaying,LatestFloatingRate,Period]
    %   = IMPORTFILE1(FILE) reads data from the first worksheet in the
    %   Microsoft Excel spreadsheet file named FILE and returns the data as
    %   column vectors.
    %
    %   [Counterparty,NettingID,Principal,Maturity,LegType,LegRateReceiving,LegRatePaying,LatestFloatingRate,Period]
    %   = IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
    %
    %   [Counterparty,NettingID,Principal,Maturity,LegType,LegRateReceiving,LegRatePaying,LatestFloatingRate,Period]
    %   = IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
    %   worksheet for the specified row interval(s). Specify STARTROW and
    %   ENDROW as a pair of scalars or vectors of matching size for
    %   dis-contiguous row intervals. To read to the end of the file specify an
    %   ENDROW of inf.%
    % Example:
    %   [Counterparty,NettingID,Principal,Maturity,LegType,LegRateReceiving,LegRatePaying,LatestFloatingRate,Period]
    %   = importfile1('CCR Data.xlsx','Swaps',2,31);
    %
    %   See also XLSREAD.
    
    % Auto-generated by MATLAB on 2013/04/19 16:22:23
    
    %% Input handling
    
    % If no sheet is specified, read first sheet
    if nargin == 1 || isempty(sheetName)
        sheetName = 1;
    end
    
    % If row start and end points are not specified, define defaults
    if nargin <= 3
        startRow = 2;
        endRow = 31;
    end
    
    %% Import the data
    [~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:I%d',startRow(1),endRow(1)));
    for block=2:length(startRow)
        [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:I%d',startRow(block),endRow(block)));
        raw = [raw;tmpRawBlock]; %#ok<AGROW>
    end
    raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
    cellVectors = raw(:,4);
    raw = raw(:,[1,2,3,5,6,7,8,9]);
    
    %% Create output variable
    data = reshape([raw{:}],size(raw));
    
    %% Allocate imported array to column variable names
    Counterparty = data(:,1);
    NettingID = data(:,2);
    Principal = data(:,3);
    Maturity = cellVectors(:,1);
    Maturity = datenum(Maturity, 'dd/mm/yyyy');
    LegType = data(:,4);
    LegRateReceiving = data(:,5);
    LegRatePaying = data(:,6);
    LatestFloatingRate = data(:,7);
    Period = data(:,8);
    
