function createEFplot(X1, Y1, pret1)
    %CREATEEFPLOT(X1,Y1,PRET1)
    %  X1:  vector of x data
    %  Y1:  vector of y data
    %  PRET1:  vector of y data
    
    %  Auto-generated by MATLAB on 26-Feb-2012 17:18:06
    
    % Create figure
    figure1 = figure;
    colormap('summer');
    
    % Create subplot
    subplot1 = subplot(2,1,1,'Parent',figure1);
    box(subplot1,'on');
    hold(subplot1,'all');
    
    % Create plot
    plot(X1,Y1,'Parent',subplot1,'LineWidth',2);
    
    % Create xlabel
    xlabel('Risk','FontWeight','bold');
    
    % Create ylabel
    ylabel('Return','FontWeight','bold');
    
    % Create title
    title('Efficient Frontier','FontWeight','bold');
    
    % Create subplot
    subplot2 = subplot(2,1,2,'Parent',figure1);
    box(subplot2,'on');
    hold(subplot2,'all');
    
    % Create plot
    plot(X1,pret1,'Parent',subplot2,'LineWidth',3,'Color',[1 0 0],...
        'DisplayName','Sharpe Ratio');
    
    % Create legend
    legend(subplot2,'show','Location','SE');
    
