function createfigure(X1, ymatrix1)
    %CREATEFIGURE(X1,YMATRIX1)
    %  X1:  stairs x
    %  YMATRIX1:  stairs matrix data
    
    %  Auto-generated by MATLAB on 25-Feb-2012 14:45:36
    
    % Create figure
    figure1 = figure;
    
    % Create axes
    axes1 = axes('Parent',figure1,...
        'XTickLabel',['1992';'1995';'1997';'2000';'2002';'2005'],...
        'XTick',[727747.5 728660 729573.5 730486 731399.5 732313]);
    % Uncomment the following line to preserve the X-limits of the axes
    % xlim(axes1,[727747.5 732313]);
    box(axes1,'on');
    hold(axes1,'all');
    
    % Create multiple lines using matrix input to stairs
    stairs1 = stairs(X1,ymatrix1,'Parent',axes1);
    set(stairs1(1),'DisplayName','Canada');
    set(stairs1(2),'DisplayName','France');
    set(stairs1(3),'DisplayName','Germany');
    set(stairs1(4),'DisplayName','Japan');
    set(stairs1(5),'DisplayName','UK');
    set(stairs1(6),'DisplayName','US');
    
    % Create xlabel
    xlabel('Date','FontWeight','bold','FontSize',12);
    
    % Create ylabel
    ylabel('Index Value','FontWeight','bold','FontSize',12);
    
    % Create title
    title('Historical Performance','FontWeight','bold','FontSize',12);
    
    % Create legend
    legend(axes1,'show');
    
