%% IMPORTFROMDB  Read historical information from a database

% First define the ODBC database source 
% Name of database source used in MATLAB: introIndexData

% Database file: IndexData.mdb
% Database table name:  indexTS

%% Set preferences with setdbprefs.
s.DataReturnFormat = 'dataset';
s.ErrorHandling = 'store';
s.NullNumberRead = 'NaN';
s.NullNumberWrite = 'NaN';
s.NullStringRead = 'null';
s.NullStringWrite = 'null';
s.JDBCDataSourceFile = '';
s.UseRegistryForSources = 'yes';
s.TempDirForRegistryOutput = 'C:\Temp';
s.DefaultRowPreFetch = '10000';
setdbprefs(s)

%% Make connection to database.  Note that the password has been omitted.
% Using ODBC driver.
conn = database('IndexData','','password'); 

%% Read data from database.
e = exec(conn,'SELECT ALL Dates,Canada,France,Germany,Japan,UK,US FROM indexTS');
e = fetch(e);
close(e)

%% Assign data to output variable.
data = e.Data;

%% Close database connection.
close(conn)

%%You can customise the autogenerated code as I have here
names = data.Properties.VarNames(2:end);  % column names
data.Dates = datenum(data.Dates,'yyyy-mm-dd HH:MM:SS.FFF');  
dates = data.Dates;
prices = double(data(:,2:end));
clearvars -except dates prices names data
nAssets = length(names);